name: wealth_wise
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  another_flushbar: ^1.12.30
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.8.4
  google_fonts: ^5.1.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets\fonts\inter\Inter-Light.ttf
          weight: 300
        - asset: assets\fonts\inter\Inter-Regular.ttf
          weight: 400
        - asset: assets\fonts\inter\Inter-Medium.ttf
          weight: 500
        - asset: assets\fonts\inter\Inter-SemiBold.ttf
          weight: 600
        - asset: assets\fonts\inter\Inter-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true
  output_dir: lib/resources/localization/generated
  arb_dir: lib/resources/localization/l10n
